/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.abdul;

import javax.swing.JOptionPane;

/**
 *
 * @author CL1-PC29
 */
public class batobatopick extends javax.swing.JFrame {

    /**
     * Creates new form batobatopick
     */
    public batobatopick() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtplayer1 = new javax.swing.JTextField();
        txtplayer2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtplayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 120, -1));
        getContentPane().add(txtplayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, -1));

        jButton1.setText("vs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel1.setText("Player 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel2.setText("Player 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel3.setText("[3] - Scissor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel4.setText("[1] - Rock");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel5.setText("[2]  - Paper");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int player1 = Integer.parseInt(txtplayer1.getText());
        int player2 = Integer.parseInt(txtplayer2.getText());
        
        if (player1 == 1 && player2 ==1 )
        {
        JOptionPane.showMessageDialog(null, "Draw", "MATCHING", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 1 && player2 ==2 )
        {
        JOptionPane.showMessageDialog(null, "Player 2 Wins", "MATCHING", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 1 && player2 ==3 )
        {
        JOptionPane.showMessageDialog(null, "Player 1 Wins", "MATCHING", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 2 && player2 ==1 )
        {
        JOptionPane.showMessageDialog(null, "Player 1 Wins", "MATCHING", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 2 && player2 ==2 )
        {
        JOptionPane.showMessageDialog(null, "Draw", "MATCHING", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 2 && player2 ==3 )
        {
        JOptionPane.showMessageDialog(null, "Player 2 Wins", "MATCHING", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 3 && player2 ==1 )
        {
        JOptionPane.showMessageDialog(null, "Player 1 Wins", "MATCHING", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 3 && player2 ==2 )
        {
        JOptionPane.showMessageDialog(null, "Player 2 Wins", "MATCHING", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (player1 == 3 && player2 ==3 )
        {
        JOptionPane.showMessageDialog(null, "Draw", "MATCHING", JOptionPane.INFORMATION_MESSAGE);
        }
        else 
        {
        JOptionPane.showMessageDialog(null, "ERROR", "MATCHING", JOptionPane.INFORMATION_MESSAGE);
        }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(batobatopick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(batobatopick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(batobatopick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(batobatopick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new batobatopick().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtplayer1;
    private javax.swing.JTextField txtplayer2;
    // End of variables declaration//GEN-END:variables
}
